# -*- coding: utf-8 -*-
"""HW5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGH6SXrvFDoVE6uwtRsDu6ilpxcNZD--

# Q1

1.1)
It keeps the model from using very large coefficients, which helps prevent overfitting and makes the model simpler.


1.2)
Regularization controls complexity. More penalty = simpler model (higher bias, lower variance). Less penalty = more flexible model (lower bias, higher variance).


1.3)
Ridge shrinks coefficients but keeps all of them.
LASSO can shrink some coefficients to zero, removing features.
Ridge keeps everything, LASSO does feature selection.


1.4)
We standardize variables (mean 0, std 1) so all features are on the same scale. This prevents some variables from being unfairly penalized more than others.


1.5)
We choose α using cross-validation by picking the value that gives the best performance.


1.6)
No. We only use prediction error (MSE) because we care about how well the model predicts new data, not the penalty.

# Q2
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/data/cars_hw.csv")

# Check columns
print(df.columns)
df.head()

df["Age"] = 2024 - df["Make_Year"]   # adjust year if needed

X = df[["Mileage_Run", "Age"]]
y = df["Price"]   # or whatever your target is

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

poly = PolynomialFeatures(degree=3, include_bias=False)
X_poly = poly.fit_transform(X)

feature_names = poly.get_feature_names_out(["Mileage_Run", "Age"])
print(feature_names)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_poly)

from sklearn.linear_model import LinearRegression

linreg = LinearRegression()
linreg.fit(X_scaled, y)

coeffs = pd.Series(linreg.coef_, index=feature_names)
print(coeffs)

"""2.2) The interaction between Mileage_Run and Age is negative."""

from sklearn.linear_model import LassoCV

alphas = np.logspace(1, 3, 20)

lasso = LassoCV(alphas=alphas, cv=20)
lasso.fit(X_scaled, y)

print("Best alpha:", lasso.alpha_)

import matplotlib.pyplot as plt

mean_mse = np.mean(lasso.mse_path_, axis=1)

plt.plot(lasso.alphas_, mean_mse)
plt.xscale("log")
plt.xlabel("Alpha")
plt.ylabel("MSE")
plt.title("Cross-validated MSE vs Alpha")
plt.show()

"""2.3) We used LassoCV with 20-fold cross-validation to choose the best α. The optimal α is the one that minimizes the cross-validated MSE (around where the curve is lowest, roughly in the mid-range of the tested values).

2.4) The MSE decreases as α increases at first, reaches a minimum, and then increases again. This shows that a moderate amount of regularization gives the best performance.
"""

from sklearn.linear_model import Lasso

coefs = []

for a in alphas:
    model = Lasso(alpha=a)
    model.fit(X_scaled, y)
    coefs.append(model.coef_)

coefs = np.array(coefs)

for i in range(coefs.shape[1]):
    plt.plot(alphas, coefs[:, i])

plt.xscale("log")
plt.xlabel("Alpha")
plt.ylabel("Coefficient value")
plt.title("Coefficient paths")
plt.show()

"""2.5) As α increases, the coefficients shrink toward zero. Some coefficients decrease steadily, while others approach zero more quickly. This shows how LASSO simplifies the model as regularization increases."""

lasso_coeffs = pd.Series(lasso.coef_, index=feature_names)

print(lasso_coeffs)
print("\nNon-zero features:")
print(lasso_coeffs[lasso_coeffs != 0])

zero_prop = np.mean(lasso_coeffs == 0)
print("\nProportion zero:", zero_prop)

"""2.6) All features are selected because none of the coefficients are equal to zero.
The proportion of coefficients set to zero is 0.0.
"""

comparison = pd.DataFrame({
    "Linear": linreg.coef_,
    "LASSO": lasso.coef_
}, index=feature_names)

print(comparison)

"""2.7)
Compared to linear regression:

Most coefficients decrease in magnitude under LASSO.
No coefficients increase significantly.
Some coefficients change slightly, but the signs mostly stay the same.

# Q3
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/data/heart_failure_clinical_records_dataset.csv")

df.head()

X_cont = df[["age", "ejection_fraction", "serum_creatinine"]]

X_cat = df[["anaemia", "diabetes", "high_blood_pressure", "smoking"]]

y = df["DEATH_EVENT"]

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

poly_cont = PolynomialFeatures(degree=3, include_bias=False)
X_cont_poly = poly_cont.fit_transform(X_cont)

cont_names = poly_cont.get_feature_names_out(["age", "ejection_fraction", "serum_creatinine"])

scaler = StandardScaler()
X_cont_scaled = scaler.fit_transform(X_cont_poly)

poly_cat = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_cat_inter = poly_cat.fit_transform(X_cat)

cat_names = poly_cat.get_feature_names_out(["anaemia", "diabetes", "high_blood_pressure", "smoking"])

X_final = np.hstack([X_cont_scaled, X_cat_inter])
feature_names = list(cont_names) + list(cat_names)

from sklearn.linear_model import LinearRegression

linreg = LinearRegression()
linreg.fit(X_final, y)

coeffs = pd.Series(linreg.coef_, index=feature_names)
print(coeffs)

"""3.2) Some coefficients look counterintuitive. For example, age has a positive coefficient, but age² is negative and age³ is positive. This seems confusing at first, but it happens because the model includes higher-order terms and interactions. These allow the relationship to be nonlinear, so the combined effect of all terms better captures the true pattern, even if individual coefficients look unusual."""

import warnings
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LassoCV
import numpy as np

warnings.filterwarnings("ignore", category=ConvergenceWarning)

alphas = np.logspace(-5, 5, 30)

lasso = LassoCV(alphas=alphas, cv=20, max_iter=10000)
lasso.fit(X_final, y)

print("Best alpha:", lasso.alpha_)

"""3.3) We used LassoCV with 20-fold cross-validation to select the best α. The optimal value was α ≈ 0.0057, which minimizes the cross-validated MSE."""

import matplotlib.pyplot as plt

mean_mse = np.mean(lasso.mse_path_, axis=1)

plt.plot(lasso.alphas_, mean_mse)
plt.xscale("log")
plt.xlabel("Alpha")
plt.ylabel("MSE")
plt.title("MSE vs Alpha")
plt.show()

"""3.4) The MSE decreases as α increases at first, reaches a minimum around α ≈ 0.0057, and then increases and levels off. This shows that a small amount of regularization gives the best performance."""

from sklearn.linear_model import Lasso

coefs = []

for a in alphas:
    model = Lasso(alpha=a, max_iter=10000)
    model.fit(X_final, y)
    coefs.append(model.coef_)

coefs = np.array(coefs)

for i in range(coefs.shape[1]):
    plt.plot(alphas, coefs[:, i])

plt.xscale("log")
plt.xlabel("Alpha")
plt.ylabel("Coefficients")
plt.title("Coefficient Paths")
plt.show()

"""3.5) As α increases, all coefficients shrink toward zero. Many coefficients drop quickly and become exactly zero, while a few remain non-zero longer. Eventually, at large α, almost all coefficients are driven to zero. This shows that LASSO performs feature selection by removing less important variables as regularization increases."""

lasso_coeffs = pd.Series(lasso.coef_, index=feature_names)

print(lasso_coeffs[lasso_coeffs != 0])

print("\nProportion zero:")
print(np.mean(lasso_coeffs == 0))

comparison = pd.DataFrame({
    "Linear": linreg.coef_,
    "LASSO": lasso.coef_
}, index=feature_names)

print(comparison)

"""3.6) The features selected by LASSO are those with non-zero coefficients, including ejection_fraction, serum_creatinine, age³, and several interaction terms.

The proportion of coefficients set to zero is approximately 0.586 (58.6%), meaning over half of the features were removed.

Compared to linear regression:

Many coefficients are reduced to zero
Remaining coefficients are smaller in magnitude
Signs mostly stay the same

The LASSO model makes more sense because it simplifies the model by removing less important features, which helps reduce overfitting and improves the bias-variance trade-off.

# Q4

### 1. Objective Function (Ridge)

$$
\min_{b_0, b_1} \frac{1}{n} \sum_{i=1}^n (\tilde{y}_i - b_0 - b_1 \tilde{x}_i)^2 + \alpha b_1^2
$$

---

### 2. Solution for \( b_0 \) and \( b_1 \)

Because the data is mean-centered:

$$
b_0 = 0
$$

$$
b_1 = \frac{\sum \tilde{x}_i \tilde{y}_i}{\sum \tilde{x}_i^2 + \alpha}
$$

---

### 3. Effect of Increasing \( \alpha \)

As \( \alpha \) increases, the denominator increases, so:

- \( b_1 \) decreases  
- The slope shrinks toward 0  

---

### 4. LASSO Challenge

With LASSO (\( +\alpha |b_1| \)):

- The objective is not differentiable at \( b_1 = 0 \)  
- We cannot solve using standard derivatives  

It is optimal to set \( b_1 = 0 \) when:

$$
\left| \sum \tilde{x}_i \tilde{y}_i \right| \le \alpha
$$

---

### Interpretation

- Ridge shrinks coefficients smoothly  
- LASSO can shrink coefficients exactly to zero (feature selection)
"""